import pytest
from unittest.mock import patch, MagicMock
from fastapi.testclient import TestClient
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from main import app


@pytest.fixture
def client():
    """Create a test client for the FastAPI app."""
    return TestClient(app)


@pytest.fixture
def mock_repo_data():
    """Mock repository data for testing."""
    return {
        "repo_info": {
            "name": "test-repo",
            "full_name": "test-user/test-repo",
            "description": "A test repository",
            "stars": 100,
            "forks": 20,
            "language": "Python",
            "default_branch": "main",
            "topics": ["test"],
            "license": "MIT",
            "created_at": "2024-01-01T00:00:00Z",
            "updated_at": "2024-01-02T00:00:00Z",
        },
        "file_tree": [
            {"path": "README.md", "type": "file", "size": 1000},
            {"path": "main.py", "type": "file", "size": 500},
        ],
        "file_contents": {
            "README.md": "# Test Repo\nThis is a test.",
            "main.py": "print('Hello, World!')",
        },
        "total_files": 2,
        "fetched_files": 2,
    }


@pytest.fixture
def mock_gemini_response():
    """Mock Gemini AI response."""
    return "This is a code explanation generated by AI."


@pytest.fixture
def mock_health_response():
    """Mock health check response."""
    return {
        "status": "ok",
        "version": "1.2.0",
        "gemini_configured": True,
        "github_configured": True,
        "available_analyses": [
            "code_explain",
            "bug_detection",
            "readme_improve",
            "architecture",
            "documentation",
            "refactoring",
            "security",
        ],
    }
